### ISSUE TITLE
The tool lacks support for ros2idl schema encoding

### ISSUE THREAD

**Issue by rachwalk** [sensmore/kappe#2]
Hi, I have an .mcap file which contains messages conformant to the ros2idl schema. The schema is officially supported in the spec -- see [here](https://github.com/ros-tooling/rosbag2_storage_mcap/issues/43).

This results in most topics of the rosbag being dropped during conversion. Is it possible to add the encoding to the supported ones for kappe?

**Comment by nirhenn** [comment]
Hi There, quick check if this topic was resolved as I am facing the same issue. Some topics are dropped as it is missing schema since they are described in ros2idl
