### ISSUE TITLE
@Dataclass not found in Python12 qot file

### ISSUE THREAD

**Issue by Humvee3982** [sensmore/kappe#6]

**Comment by mrkbac** [comment]
Hi @Humvee3982, could you share the exact output, as well as your kappe version?

**Comment by Humvee3982** [comment]
I installed the newest PyPi Version on newest Ubuntu Version (v0.15.0).
Error could be solved for me by manualy editing the library and removing @dataclass and adding an __init__ with the parameters. I tried with Python v1.12

**Comment by mrkbac** [comment]
I've published a new version, let me know if it fixes you probleme
